
String APIKEY="ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRjd05qRXdMQ0p1WVcxbElqb2lhVzVwZEdsaGJDSjkuUElTdHZuNUsyY21tV3VEem0yblpRdmw5dkhkOVZLc1hmNEpueFVma2JTR0VVTndlamRycXh0a2tFbDVEeDJ5RUFzWXV6WURnaDhSSDB4NGFZcWtpQ2c=";

String PAYMENT_FIRST_TOKEN='';
String PAYMENT_ORDER_ID='';

String PAYMENT_FINAL_TOKEN_VISA='';
String PAYMENT_FINAL_TOKEN_KIOSK='';

String REFCODE='';

String INTGRATION_ID_VISACARD='2010893';
String INTGRATION_ID_KIOSK='2011150';